import os
import re
import json
import logging
from datetime import datetime
from werkzeug.utils import secure_filename
from flask_login import current_user

# File upload configurations
ALLOWED_EXTENSIONS = {'pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'mp4', 'mov', 'mp3', 'wav', 'txt', 'rtf', 'm4a', 'ogg', 'aac', 'flac', 'wma', 'avi', 'wmv', 'flv', 'webm'}

def allowed_file(filename):
    """Check if the file type is allowed for upload."""
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

def get_file_type(filename):
    """Get the general file type category (document, image, video, audio, other)."""
    if '.' not in filename:
        return 'unknown'
    
    ext = filename.rsplit('.', 1)[1].lower()
    if ext in {'pdf', 'doc', 'docx', 'txt', 'rtf'}:
        return 'document'
    elif ext in {'jpg', 'jpeg', 'png', 'gif', 'bmp'}:
        return 'image'
    elif ext in {'mp4', 'mov', 'avi', 'wmv', 'flv', 'webm'}:
        return 'video'
    elif ext in {'mp3', 'wav', 'ogg', 'm4a', 'aac', 'flac', 'wma'}:
        return 'audio'
    else:
        return 'other'

def generate_filename(case_name, form_type, state):
    """Generate a standardized filename for a legal document."""
    # Clean the case name for use in filename
    clean_name = re.sub(r'[^\w\s-]', '', case_name).strip().replace(' ', '_')
    
    # Get form type in a readable format
    form_name = form_type.replace('_', ' ').title()
    
    # Generate filename with timestamp to ensure uniqueness
    timestamp = datetime.utcnow().strftime('%Y%m%d%H%M%S')
    filename = f"{clean_name}_{form_name}_{state}_{timestamp}.pdf"
    
    return filename

def generate_document(form_type, case, state, court_type, deadline_date=None):
    """Generate document content based on form type and case details."""
    # Get detailed rationale and strategic guidance for this document
    document_explanation = get_document_explanation(form_type, case.issue_type, court_type)
    
    # Basic document header
    content = f"""
DOCUMENT TYPE: {form_type.replace('_', ' ').title()}
STATE: {state}
COURT TYPE: {court_type.replace('_', ' ').title()}
CASE TITLE: {case.title}
ISSUE TYPE: {case.issue_type.replace('_', ' ').title()}

STRATEGIC PURPOSE OF THIS DOCUMENT:
{document_explanation['purpose']}

WHY THIS DOCUMENT IS CRITICAL:
{document_explanation['importance']}

TACTICAL FILING CONSIDERATIONS:
{document_explanation['tactical_considerations']}

DOCUMENT CONTENT FOLLOWS:
==========================================================================

"""
    
    if deadline_date:
        content += f"DEADLINE DATE: {deadline_date.strftime('%B %d, %Y')}\n\n"
    
    # Add form-specific content
    if form_type == 'motion_to_quash':
        content += generate_motion_to_quash(case, state, court_type)
    elif form_type == 'civil_cover_sheet':
        content += generate_civil_cover_sheet(case, state, court_type)
    elif form_type == 'section_1983':
        content += generate_section_1983_complaint(case, state, court_type)
    elif form_type == 'habeas_corpus':
        content += generate_habeas_corpus(case, state, court_type)
    elif form_type == 'discovery_request':
        content += generate_discovery_request(case, state, court_type)
    elif form_type == 'motion_to_dismiss':
        content += generate_motion_to_dismiss(case, state, court_type)
    elif form_type == 'answer_complaint':
        content += generate_answer_complaint(case, state, court_type)
    else:
        content += "DOCUMENT TEMPLATE NOT FOUND. Please contact support."
    
    # Add footnote with tactical advice
    content += f"""
==========================================================================

TACTICAL FILING ADVICE:
{document_explanation['filing_advice']}

WHAT TO EXPECT AFTER FILING:
{document_explanation['next_steps']}

POTENTIAL CHALLENGES AND RESPONSES:
{document_explanation['potential_challenges']}

Document generated by Due Process AI on {datetime.utcnow().strftime('%B %d, %Y at %H:%M:%S UTC')}
This document is for informational purposes only and does not constitute legal advice.
"""
    
    return content

def get_document_explanation(form_type, issue_type, court_type):
    """
    Provide detailed explanations about the purpose, importance and tactical considerations
    for each document type.
    """
    explanations = {
        'motion_to_quash': {
            'purpose': 'This motion challenges the legal validity of a search warrant, arrest warrant, or subpoena. It seeks to invalidate evidence obtained through these means.',
            'importance': 'A successful motion to quash prevents the prosecution from using potentially damaging evidence against you, and may lead to case dismissal if the evidence is central to their case.',
            'tactical_considerations': 'The timing of this motion is critical - it must be filed before trial and ideally as early as possible in the proceedings to prevent the evidence from influencing other aspects of your case.',
            'filing_advice': 'This motion should be filed immediately after receiving discovery that reveals potential Fourth Amendment violations. Attach any relevant evidence showing the warrant was defective.',
            'next_steps': 'The court will likely schedule a hearing where you must be prepared to argue the specific legal defects in the warrant. Be ready to cite relevant case law.',
            'potential_challenges': 'The prosecution may argue "good faith exception" or other exceptions to the warrant requirement. Counter by demonstrating how the specific facts of your case do not qualify for these exceptions.'
        },
        'civil_cover_sheet': {
            'purpose': 'This administrative document provides the court with essential case information and helps determine proper case assignment and statistical tracking.',
            'importance': 'While seemingly routine, errors on this form can cause delays or even improper jurisdiction assignment, potentially jeopardizing your case.',
            'tactical_considerations': 'Selecting the proper jurisdiction, nature of suit, and demand amount can impact how your case proceeds and which judge might be assigned to your case.',
            'filing_advice': 'Complete this form with absolute accuracy. For civil rights cases, ensure you select the correct nature of suit code (typically 440 for civil rights or 550 for prisoner petitions).',
            'next_steps': 'This document is typically filed with your initial complaint. The court clerk will use it to process your case opening.',
            'potential_challenges': 'The clerk may reject filings with incomplete or incorrect cover sheets. Double-check every field before submission.'
        },
        'section_1983': {
            'purpose': 'This federal civil rights complaint allows you to sue government officials or entities that violated your constitutional rights while acting "under color of law."',
            'importance': 'This powerful legal tool provides monetary damages and injunctive relief against government actors who violated your constitutional rights.',
            'tactical_considerations': 'Individual capacity claims allow for monetary damages, while official capacity claims are essentially against the government entity itself and may be limited by sovereign immunity.',
            'filing_advice': 'Be extremely specific about which constitutional rights were violated, which defendants violated them, and how. Link each defendant to specific actions that violated specific rights.',
            'next_steps': 'After filing, defendants will likely file motions to dismiss, often claiming qualified immunity. Be prepared with specific case law showing your rights were "clearly established."',
            'potential_challenges': 'Qualified immunity is a major hurdle - you must show the defendant violated "clearly established" law that a reasonable person would have known about.'
        },
        'habeas_corpus': {
            'purpose': 'This petition challenges the legality of your detention or imprisonment, arguing that your confinement violates constitutional rights or statutory law.',
            'importance': 'This is often your last chance to challenge a conviction after direct appeals have been exhausted, especially when new evidence emerges or constitutional violations are discovered.',
            'tactical_considerations': 'Strict filing deadlines apply - federal habeas petitions under 28 U.S.C. § 2254 typically must be filed within one year of conviction finality.',
            'filing_advice': 'Focus on constitutional violations that affected the outcome of your case, exhaust all state remedies first, and be mindful of procedural rules like the one-year filing deadline.',
            'next_steps': 'The court may dismiss the petition, order the government to respond, or schedule an evidentiary hearing. Be prepared for a potentially lengthy process.',
            'potential_challenges': 'Procedural defaults, failure to exhaust state remedies, and deference to state court findings are common obstacles.'
        },
        'discovery_request': {
            'purpose': 'This document formally requests evidence and information from the opposing party, including documents, answers to written questions, and physical evidence.',
            'importance': 'Effective discovery is crucial for building your case, identifying weaknesses in the opposition\'s position, and uncovering evidence of rights violations.',
            'tactical_considerations': 'Specific, targeted requests are more likely to yield useful information and survive objections than overly broad "fishing expeditions."',
            'filing_advice': 'Be precise in your requests. For criminal cases, focus on Brady material (exculpatory evidence), chain of custody documents, and anything that could reveal Fourth Amendment violations.',
            'next_steps': 'The opposing party must respond within a set timeframe (typically 30 days). Be prepared to file motions to compel if they object unreasonably.',
            'potential_challenges': 'Expect objections based on relevance, privilege, or burden. Be ready to explain why each item requested is directly relevant to your case.'
        },
        'motion_to_dismiss': {
            'purpose': 'This motion asks the court to dismiss a case before trial, arguing that even if all allegations were true, there is no legal basis for the case to proceed.',
            'importance': 'A successful motion to dismiss ends the case early, saving time, resources, and preventing the stress of continued litigation.',
            'tactical_considerations': 'This is typically filed at the earliest stages of litigation, before significant discovery or other proceedings occur.',
            'filing_advice': 'Focus on legal defects rather than factual disputes. Common grounds include lack of jurisdiction, failure to state a claim, statutory immunity, or expiration of statute of limitations.',
            'next_steps': 'The court may schedule oral arguments or rule based on the papers. If denied, the case proceeds to discovery; if granted, the case may end or the plaintiff may be given leave to amend.',
            'potential_challenges': 'Courts often interpret complaints in the light most favorable to the non-moving party, making dismissal relatively difficult at early stages.'
        },
        'answer_complaint': {
            'purpose': 'This formal response to a civil complaint addresses each allegation, asserts defenses, and preserves your rights in the litigation.',
            'importance': 'Failing to properly answer can result in default judgment against you. This document shapes the entire direction of your defense.',
            'tactical_considerations': 'Strict deadlines apply - typically 21 days after service. Missing this deadline could result in default judgment.',
            'filing_advice': 'Respond to each numbered paragraph in the complaint with an admission, denial, or statement that you lack sufficient information. Then list all applicable affirmative defenses.',
            'next_steps': 'After filing, the case typically moves to the discovery phase where both parties exchange information and evidence.',
            'potential_challenges': 'Failing to raise certain defenses in your answer may waive them forever. Consult comprehensive lists of affirmative defenses to ensure none are missed.'
        }
    }
    
    # Return the explanation for the requested document type, or a generic one if not found
    return explanations.get(form_type, {
        'purpose': 'This document serves a specific legal purpose in your case.',
        'importance': 'The document may be important for preserving your rights.',
        'tactical_considerations': 'Consider the timing and content carefully when filing this document.',
        'filing_advice': 'Ensure all required elements are included and the document is filed according to court rules.',
        'next_steps': 'After filing, monitor for responses from other parties or the court.',
        'potential_challenges': 'Be prepared to address any objections or challenges to your filing.'
    })

def generate_motion_to_quash(case, state, court_type):
    """Generate a Motion to Quash Warrant."""
    return f"""[IN THE {court_type.replace('_', ' ').upper()} COURT OF {state.upper()}]

[CASE CAPTION/HEADER]
{case.title}
Case No. [CASE NUMBER]

MOTION TO QUASH WARRANT

COMES NOW the Defendant, appearing pro se, and respectfully moves this Honorable Court for an Order quashing the search/arrest warrant issued in this case. In support of this Motion, the Defendant states as follows:

STATEMENT OF FACTS

1. On or about [DATE], a warrant was issued for [search of property/arrest] of the Defendant.

2. This warrant was issued based on an affidavit from [OFFICER NAME] that contains multiple factual inaccuracies and fails to establish probable cause.

3. Specifically, the warrant and/or its execution was defective for the following reasons:
   • The affidavit contained materially false statements and/or omissions;
   • The warrant was overbroad and did not particularly describe the places to be searched or things to be seized;
   • The officers exceeded the scope of the warrant during execution;
   • The warrant was based on stale information;
   • The warrant was executed without proper announcement and entry procedures.

LEGAL ARGUMENT

I. The Warrant Was Issued Without Sufficient Probable Cause

The Fourth Amendment requires that no warrant shall issue without probable cause, supported by oath or affirmation. In this case, the affidavit supporting the warrant failed to establish probable cause because [SPECIFIC REASONS tailored to case].

The Supreme Court in Illinois v. Gates, 462 U.S. 213 (1983), established that probable cause determinations require evaluation of the "totality of the circumstances." Here, the totality of circumstances fails to establish probable cause because [REASONS].

II. The Warrant Failed To Particularly Describe The Places To Be Searched And Things To Be Seized

The Fourth Amendment requires that warrants must "particularly describ[e] the place to be searched, and the persons or things to be seized." This warrant failed this requirement because [SPECIFIC REASONS].

III. Fruit of the Poisonous Tree

Under the doctrine established in Wong Sun v. United States, 371 U.S. 471 (1963), all evidence obtained as a result of an illegal search or seizure must be suppressed as "fruit of the poisonous tree." Therefore, all evidence obtained directly or indirectly from this defective warrant must be suppressed.

PRAYER FOR RELIEF

WHEREFORE, the Defendant respectfully requests that this Court:

1. Grant this Motion and quash the warrant issued in this case;
2. Suppress all evidence obtained directly or indirectly as a result of the warrant;
3. Schedule a hearing on this Motion; and
4. Grant such other relief as the Court deems just and proper.

Respectfully submitted,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR PHONE]
[YOUR EMAIL]

Date: [CURRENT DATE]

CERTIFICATE OF SERVICE

I hereby certify that a true and correct copy of the foregoing Motion to Quash Warrant was served upon [PROSECUTOR'S OFFICE] on this [DATE] by [METHOD OF SERVICE].

[YOUR NAME]
"""

def generate_civil_cover_sheet(case, state, court_type):
    """Generate a Civil Cover Sheet."""
    return f"""CIVIL COVER SHEET

I. (a) PLAINTIFFS
[YOUR NAME]

(b) County of Residence of First Listed Plaintiff: [YOUR COUNTY]

(c) Attorneys (Firm Name, Address, and Telephone Number)
Pro Se (Self-Represented)

II. BASIS OF JURISDICTION
[] 1 U.S. Government Plaintiff
[] 2 U.S. Government Defendant
[X] 3 Federal Question (For Civil Rights/Constitutional Claims)
[] 4 Diversity (For State Law Claims)

III. CITIZENSHIP OF PRINCIPAL PARTIES
(Place an "X" in One Box for Plaintiff and One Box for Defendant)
Plaintiff:
[] 1 Citizen of This State
[] 2 Citizen of Another State
[] 3 Citizen or Subject of a Foreign Country

Defendant:
[] 1 Incorporated in This State
[] 2 Incorporated in Another State
[] 3 Foreign Nation

IV. NATURE OF SUIT
[X] 440 Other Civil Rights
[] 550 Prisoner Petitions - Civil Rights
[] 555 Prison Conditions 
[] Other: [SPECIFY]

V. ORIGIN
[X] 1 Original Proceeding
[] 2 Removed from State Court
[] 3 Remanded from Appellate Court
[] 4 Reinstated or Reopened
[] 5 Transferred from Another District
[] 6 Multidistrict Litigation

VI. CAUSE OF ACTION
Brief description of cause:
Civil rights action under 42 U.S.C. § 1983 for violations of constitutional rights related to {case.description[0:100]}...

VII. REQUESTED IN COMPLAINT
[] CHECK IF THIS IS A CLASS ACTION    DEMAND $: [AMOUNT]    [] CHECK YES only if demanded in complaint
UNDER RULE 23, F.R.Cv.P.                                    JURY DEMAND:  [X] Yes  [] No

VIII. RELATED CASE(S) IF ANY
Judge: [JUDGE NAME]    Docket Number: [RELATED CASE NUMBER]

DATE: [CURRENT DATE]    SIGNATURE OF ATTORNEY OF RECORD: [SIGNATURE]
"""

def generate_section_1983_complaint(case, state, court_type):
    """Generate a Section 1983 Civil Rights Complaint."""
    return f"""[IN THE {court_type.replace('_', ' ').upper()} COURT OF {state.upper()}]

[CASE CAPTION/HEADER]
[YOUR NAME],
                                      Plaintiff,
v.

[DEFENDANT NAMES],
                                      Defendants.

CIVIL ACTION NO. [LEAVE BLANK FOR COURT TO ASSIGN]

COMPLAINT FOR VIOLATION OF CIVIL RIGHTS
(42 U.S.C. § 1983)

I. JURISDICTION AND VENUE

1. This action arises under 42 U.S.C. § 1983 and the [RELEVANT CONSTITUTIONAL AMENDMENTS: Fourth, Fifth, Sixth, Eighth, Fourteenth] Amendment(s) to the United States Constitution.

2. This Court has jurisdiction over these claims pursuant to 28 U.S.C. §§ 1331 and 1343.

3. Venue is proper in this district pursuant to 28 U.S.C. § 1391(b) because the events giving rise to this claim occurred within this district and/or the defendants reside in this district.

II. PARTIES

4. Plaintiff {current_user.username if hasattr(current_user, 'username') else '[YOUR NAME]'} is a citizen of [STATE], residing at [ADDRESS].

5. Defendant [DEFENDANT #1 NAME] is a [POSITION/TITLE] employed by [AGENCY/DEPARTMENT] and was acting under color of state law at all times relevant to this complaint. Defendant is sued in [his/her] [individual/official/both] capacity.

[REPEAT FOR EACH DEFENDANT]

III. STATEMENT OF FACTS

6. On or about [DATE], Plaintiff was [DESCRIBE SITUATION GIVING RISE TO CONSTITUTIONAL VIOLATION].

7. Defendant(s) [DESCRIBE SPECIFIC ACTIONS OF EACH DEFENDANT THAT VIOLATED CONSTITUTIONAL RIGHTS].

8. As a result of Defendants' actions, Plaintiff suffered [DESCRIBE INJURIES, DAMAGES, AND HARM SUFFERED].

IV. CAUSES OF ACTION

COUNT I: VIOLATION OF FOURTH AMENDMENT RIGHTS
[IF APPLICABLE - UNLAWFUL SEARCH/SEIZURE/EXCESSIVE FORCE]

9. Plaintiff re-alleges and incorporates by reference paragraphs 1-8 above.

10. Defendant(s) violated Plaintiff's Fourth Amendment rights by [SPECIFIC VIOLATION].

11. Defendant(s) acted willfully, knowingly, and with reckless disregard for Plaintiff's constitutional rights.

12. As a direct and proximate result of these violations, Plaintiff suffered damages including [LIST DAMAGES].

COUNT II: VIOLATION OF DUE PROCESS RIGHTS
[IF APPLICABLE]

13. Plaintiff re-alleges and incorporates by reference paragraphs 1-8 above.

14. Defendant(s) violated Plaintiff's [Fifth/Fourteenth] Amendment right to due process by [SPECIFIC VIOLATION].

15. Defendant(s) acted willfully, knowingly, and with reckless disregard for Plaintiff's constitutional rights.

16. As a direct and proximate result of these violations, Plaintiff suffered damages including [LIST DAMAGES].

[ADD ADDITIONAL COUNTS AS NECESSARY]

V. PRAYER FOR RELIEF

WHEREFORE, Plaintiff respectfully requests that this Court:

a. Enter judgment declaring that Defendant(s) violated Plaintiff's constitutional rights;

b. Award compensatory damages in the amount of $[AMOUNT] for [PHYSICAL INJURIES, PAIN AND SUFFERING, EMOTIONAL DISTRESS, ETC.];

c. Award punitive damages against the individual Defendants in the amount of $[AMOUNT];

d. Award Plaintiff reasonable attorney's fees and costs pursuant to 42 U.S.C. § 1988; and

e. Grant such other relief as this Court deems just and proper.

VI. JURY DEMAND

Plaintiff demands trial by jury on all issues so triable.

Respectfully submitted,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR PHONE]
[YOUR EMAIL]

Date: [CURRENT DATE]
"""

def generate_habeas_corpus(case, state, court_type):
    """Generate a Habeas Corpus Petition."""
    return f"""[IN THE {court_type.replace('_', ' ').upper()} COURT OF {state.upper()}]

[CASE CAPTION/HEADER]
IN RE: {current_user.username.upper() if hasattr(current_user, 'username') else '[YOUR NAME]'},
                                      Petitioner.

CASE NO. [LEAVE BLANK FOR COURT TO ASSIGN]

PETITION FOR WRIT OF HABEAS CORPUS
[28 U.S.C. § 2254 FOR STATE CONVICTIONS OR § 2255 FOR FEDERAL CONVICTIONS]

I. INTRODUCTION

1. Petitioner {current_user.username if hasattr(current_user, 'username') else '[YOUR NAME]'} is currently [in custody at/subject to] [FACILITY/DETENTION CENTER/PROBATION REQUIREMENTS] pursuant to a judgment of the [COURT THAT SENTENCED YOU].

2. Petitioner was convicted of [CHARGES/OFFENSES] on [DATE] and sentenced to [SENTENCE DETAILS] on [DATE].

3. Petitioner brings this action under [28 U.S.C. § 2254 OR § 2255] challenging the constitutionality of [his/her] conviction and sentence.

II. JURISDICTION

4. This Court has jurisdiction over this petition pursuant to [28 U.S.C. § 2254 OR § 2255] and Art. I, § 9, cl. 2 of the United States Constitution (the Suspension Clause).

III. PROCEDURAL HISTORY

5. Petitioner was [arrested/indicted] on [DATE] in [COUNTY, STATE].

6. Petitioner was convicted following a [jury trial/bench trial/guilty plea] on [DATE].

7. Petitioner was sentenced on [DATE] to [SENTENCE DETAILS].

8. Petitioner [did/did not] appeal the conviction. [IF APPEALED, PROVIDE DETAILS INCLUDING DATES, COURT, AND OUTCOME].

9. Petitioner [did/did not] file post-conviction motions. [IF FILED, PROVIDE DETAILS INCLUDING DATES, COURT, AND OUTCOME].

IV. GROUNDS FOR RELIEF

GROUND ONE: [SPECIFIC CONSTITUTIONAL VIOLATION, e.g., "INEFFECTIVE ASSISTANCE OF COUNSEL IN VIOLATION OF THE SIXTH AMENDMENT"]

10. Supporting Facts: [DETAILED FACTUAL BASIS FOR THIS CLAIM]

11. This claim was [exhausted/not exhausted] in state court. [IF EXHAUSTED, EXPLAIN HOW; IF NOT, EXPLAIN WHY THE EXHAUSTION REQUIREMENT SHOULD BE EXCUSED]

GROUND TWO: [SECOND CONSTITUTIONAL VIOLATION, e.g., "FOURTH AMENDMENT VIOLATION DUE TO ILLEGAL SEARCH AND SEIZURE"]

12. Supporting Facts: [DETAILED FACTUAL BASIS FOR THIS CLAIM]

13. This claim was [exhausted/not exhausted] in state court. [IF EXHAUSTED, EXPLAIN HOW; IF NOT, EXPLAIN WHY THE EXHAUSTION REQUIREMENT SHOULD BE EXCUSED]

[ADD ADDITIONAL GROUNDS AS NECESSARY]

V. TIMELINESS

14. This petition is timely filed under [28 U.S.C. § 2244(d) OR § 2255(f)] because [EXPLAIN WHY PETITION IS WITHIN ONE-YEAR LIMITATION PERIOD].

VI. PRAYER FOR RELIEF

WHEREFORE, Petitioner respectfully requests that this Court:

a. Issue a Writ of Habeas Corpus directing Respondent to release Petitioner from custody;

b. Alternatively, order a new trial or new sentencing hearing;

c. Grant an evidentiary hearing on the claims raised in this petition; and

d. Grant such other relief as the Court deems just and proper.

Respectfully submitted,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR PHONE]
[YOUR EMAIL]

Date: [CURRENT DATE]

VERIFICATION

I, {current_user.username if hasattr(current_user, 'username') else '[YOUR NAME]'}, verify that I have read the foregoing Petition for Writ of Habeas Corpus and that the facts stated in it are true and correct to the best of my knowledge, information, and belief. I understand that false statements herein are made subject to the penalties of perjury.

[YOUR SIGNATURE]
Date: [CURRENT DATE]
"""

def generate_discovery_request(case, state, court_type):
    """Generate a Discovery Request."""
    return f"""[IN THE {court_type.replace('_', ' ').upper()} COURT OF {state.upper()}]

[CASE CAPTION/HEADER]
{case.title}
Case No. [CASE NUMBER]

REQUEST FOR PRODUCTION OF DOCUMENTS
AND TANGIBLE THINGS

TO: [OPPOSING PARTY/COUNSEL]

Pursuant to [APPLICABLE RULES OF CIVIL/CRIMINAL PROCEDURE], the [Plaintiff/Defendant], {current_user.username if hasattr(current_user, 'username') else '[YOUR NAME]'}, hereby requests that [OPPOSING PARTY] produce and permit inspection and copying of the following documents and tangible things within thirty (30) days of service of this request:

DEFINITIONS

1. "Document" means any written, recorded, or graphic matter, however produced or reproduced, including but not limited to correspondence, memoranda, notes, electronic mail, text messages, photographs, audio recordings, video recordings, computer files, and any other data compilations from which information can be obtained.

2. "Concerning" or "relating to" means referring to, describing, evidencing, constituting, reflecting, containing, analyzing, listing, mentioning, or pertaining to, in whole or in part.

3. "You" and "Your" refer to [OPPOSING PARTY] and any agents, employees, attorneys, or representatives acting on your behalf.

INSTRUCTIONS

1. These requests are continuing in nature, and you are required to supplement your responses promptly if you obtain additional information responsive to these requests.

2. If you object to any part of a request, state specifically the grounds for your objection. If you object to part of a request and not to all of it, produce all documents to which you do not object.

3. If you withhold any documents based on a claim of privilege, provide a privilege log identifying each document and the specific privilege asserted.

4. Unless otherwise specified, these requests seek documents from [RELEVANT TIME PERIOD].

REQUESTS FOR PRODUCTION

REQUEST NO. 1: Any and all incident reports, arrest reports, police reports, investigative reports, or similar documents concerning the events described in the [complaint/indictment/information].

REQUEST NO. 2: Any and all warrants (search, arrest, etc.) and supporting affidavits related to this case, including any applications, returns, and inventories.

REQUEST NO. 3: Any and all written or recorded statements made by any party or witness to this case.

REQUEST NO. 4: Any and all photographs, videos, audio recordings, diagrams, or other visual or audio representations regarding the [incident/arrest/search] at issue in this case.

REQUEST NO. 5: Any and all documents showing the chain of custody for any physical evidence seized or collected related to this case.

REQUEST NO. 6: Any and all documentation regarding the training, qualifications, disciplinary history, and complaint history of any [law enforcement officers/government officials] involved in the events at issue.

REQUEST NO. 7: Any and all internal policies, procedures, guidelines, or directives applicable to the [type of incident] at issue in this case.

REQUEST NO. 8: Any and all communications between [relevant parties] concerning the subject matter of this case.

REQUEST NO. 9: Any and all documents that you intend to use at any hearing or trial in this matter.

REQUEST NO. 10: Any and all exculpatory or impeachment evidence as required to be disclosed under [Brady v. Maryland, 373 U.S. 83 (1963)/Giglio v. United States, 405 U.S. 150 (1972)].

[ADD ADDITIONAL REQUESTS AS RELEVANT TO THE SPECIFIC CASE]

Respectfully submitted,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR PHONE]
[YOUR EMAIL]

Date: [CURRENT DATE]

CERTIFICATE OF SERVICE

I hereby certify that a true and correct copy of the foregoing Request for Production of Documents and Tangible Things was served upon [OPPOSING PARTY/COUNSEL] on this [DATE] by [METHOD OF SERVICE].

[YOUR NAME]
"""

def generate_motion_to_dismiss(case, state, court_type):
    """Generate a Motion to Dismiss."""
    return f"""[IN THE {court_type.replace('_', ' ').upper()} COURT OF {state.upper()}]

[CASE CAPTION/HEADER]
{case.title}
Case No. [CASE NUMBER]

MOTION TO DISMISS

COMES NOW the Defendant, {current_user.username if hasattr(current_user, 'username') else '[YOUR NAME]'}, appearing pro se, and moves this Honorable Court to dismiss the [charges/complaint] against [him/her]. In support of this Motion, the Defendant states as follows:

INTRODUCTION

1. Defendant is currently charged with [CHARGES/ALLEGATIONS].

2. This Motion seeks dismissal based on [BRIEF SUMMARY OF GROUNDS: e.g., violation of speedy trial rights, failure to state a claim, lack of probable cause, etc.].

STATEMENT OF FACTS

3. [RELEVANT FACTUAL BACKGROUND]

4. [IMPORTANT DATES AND TIMELINE]

5. [PROCEDURAL HISTORY]

LEGAL ARGUMENT

I. The [Charges/Complaint] Should Be Dismissed Based On Violation Of Defendant's Right To A Speedy Trial

6. The Sixth Amendment to the United States Constitution and [RELEVANT STATE LAW] guarantee criminal defendants the right to a speedy trial.

7. In this case, [NUMBER] days have elapsed since [ARREST/INDICTMENT/INITIAL APPEARANCE], well beyond the [STATUTORY/CONSTITUTIONAL] speedy trial limit of [NUMBER] days.

8. Under Barker v. Wingo, 407 U.S. 514 (1972), courts consider four factors in determining whether a defendant's speedy trial rights have been violated: (1) the length of delay; (2) the reason for the delay; (3) the defendant's assertion of the right; and (4) prejudice to the defendant.

9. Analysis of these factors in this case clearly demonstrates a violation of Defendant's speedy trial rights because:
   a. The length of delay is presumptively prejudicial;
   b. The delay is attributable to the government, not the defense;
   c. Defendant has repeatedly asserted the right to a speedy trial; and
   d. Defendant has suffered prejudice including [DESCRIBE PREJUDICE: e.g., prolonged pretrial detention, anxiety, impairment of defense, etc.].

II. The [Charges/Complaint] Should Be Dismissed For Lack Of Probable Cause

10. The Fourth Amendment requires that arrests and prosecutions be supported by probable cause.

11. In this case, the [WARRANT/COMPLAINT/CHARGING DOCUMENT] fails to establish probable cause because [SPECIFIC DEFICIENCIES].

12. The allegations are based on [INADMISSIBLE EVIDENCE, UNRELIABLE INFORMANTS, STALE INFORMATION, etc.].

13. Without probable cause, the charges cannot proceed and must be dismissed.

[ADD ADDITIONAL GROUNDS FOR DISMISSAL AS APPLICABLE]

PRAYER FOR RELIEF

WHEREFORE, for the foregoing reasons, Defendant respectfully requests that this Court:

1. Grant this Motion and dismiss all charges with prejudice;

2. Schedule a hearing on this Motion; and

3. Grant such other relief as the Court deems just and proper.

Respectfully submitted,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR PHONE]
[YOUR EMAIL]

Date: [CURRENT DATE]

CERTIFICATE OF SERVICE

I hereby certify that a true and correct copy of the foregoing Motion to Dismiss was served upon [PROSECUTOR'S OFFICE] on this [DATE] by [METHOD OF SERVICE].

[YOUR NAME]
"""

def generate_answer_complaint(case, state, court_type):
    """Generate an Answer to Complaint."""
    return f"""[IN THE {court_type.replace('_', ' ').upper()} COURT OF {state.upper()}]

[CASE CAPTION/HEADER]
{case.title}
Case No. [CASE NUMBER]

ANSWER TO COMPLAINT

COMES NOW the Defendant, {current_user.username if hasattr(current_user, 'username') else '[YOUR NAME]'}, appearing pro se, and for [his/her] Answer to Plaintiff's Complaint, states as follows:

RESPONSE TO SPECIFIC ALLEGATIONS

1. Regarding paragraph 1 of the Complaint, Defendant [ADMITS/DENIES/ADMITS IN PART AND DENIES IN PART/LACKS SUFFICIENT INFORMATION TO ADMIT OR DENY] the allegations contained therein. [IF PARTIAL ADMISSION/DENIAL, SPECIFY WHICH PORTIONS]

2. Regarding paragraph 2 of the Complaint, Defendant [ADMITS/DENIES/ADMITS IN PART AND DENIES IN PART/LACKS SUFFICIENT INFORMATION TO ADMIT OR DENY] the allegations contained therein. [IF PARTIAL ADMISSION/DENIAL, SPECIFY WHICH PORTIONS]

[CONTINUE FOR EACH PARAGRAPH OF THE COMPLAINT]

AFFIRMATIVE DEFENSES

FIRST DEFENSE

The Complaint fails to state a claim upon which relief can be granted.

SECOND DEFENSE

Plaintiff's claims are barred, in whole or in part, by the applicable statute of limitations.

THIRD DEFENSE

Plaintiff has failed to mitigate [his/her] damages, if any.

FOURTH DEFENSE

Plaintiff's claims are barred by the doctrine of unclean hands.

FIFTH DEFENSE

Plaintiff's claims are barred by the doctrine of laches.

SIXTH DEFENSE

Plaintiff's claims are barred by the doctrine of estoppel.

SEVENTH DEFENSE

Plaintiff's claims are barred by the doctrine of waiver.

EIGHTH DEFENSE

Any injuries or damages sustained by Plaintiff were caused, in whole or in part, by Plaintiff's own negligence or wrongful conduct.

NINTH DEFENSE

Any alleged contract upon which Plaintiff relies was obtained through fraud, duress, or undue influence.

TENTH DEFENSE

Defendant reserves the right to assert additional affirmative defenses as they become apparent through discovery and investigation.

WHEREFORE, Defendant respectfully requests that this Court:

1. Dismiss Plaintiff's Complaint with prejudice;

2. Award Defendant costs and reasonable attorney's fees incurred in defending this action; and

3. Grant such other relief as the Court deems just and proper.

Respectfully submitted,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR PHONE]
[YOUR EMAIL]

Date: [CURRENT DATE]

CERTIFICATE OF SERVICE

I hereby certify that a true and correct copy of the foregoing Answer to Complaint was served upon [PLAINTIFF/PLAINTIFF'S COUNSEL] on this [DATE] by [METHOD OF SERVICE].

[YOUR NAME]
"""