"""Initial migration

Revision ID: 4a915f18fc29
Revises: 
Create Date: 2025-05-09 19:04:33.376990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a915f18fc29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_analysis', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('legal_strategy', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('precedent_cases', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('success_probability', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('success_probability')
        batch_op.drop_column('precedent_cases')
        batch_op.drop_column('legal_strategy')
        batch_op.drop_column('ai_analysis')

    # ### end Alembic commands ###
