"""Initial migration

Revision ID: 522f6e479acf
Revises: 4a915f18fc29
Create Date: 2025-05-10 18:59:59.427647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522f6e479acf'
down_revision = '4a915f18fc29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('legal_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('success_probability', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('probability_factors', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('probability_suggestions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('legal_analysis', schema=None) as batch_op:
        batch_op.drop_column('probability_suggestions')
        batch_op.drop_column('probability_factors')
        batch_op.drop_column('success_probability')

    # ### end Alembic commands ###
